version: '3.8'
services:
  mysql_server:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: picpaydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - 8084:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql_server
    depends_on:
      - mysql_server
    networks:
      - adminer-network
volumes:
  mysql-data:

networks:
  adminer-network:
